-- ======================================
-- TABLAS
-- ========================================
CREATE TABLE provincia(
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE usuario(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(100) NOT NULL,
                        email VARCHAR(100) UNIQUE NOT NULL,
                        password VARCHAR(255) NOT NULL
);

CREATE TABLE grupo(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nome VARCHAR(100) NOT NULL,
                      tipo VARCHAR(50),
                      orixen VARCHAR(100)
);

CREATE TABLE foliada(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME,
    lugar VARCHAR(150),
    descripcion TEXT,
    latitude DECIMAL(9,6),
    lonxitude DECIMAL(9,6),
    provincia_id INTEGER,
    imaxe VARCHAR(255),
    CONSTRAINT fk_provincia FOREIGN KEY (provincia_id)
        REFERENCES provincia(id) ON DELETE SET NULL
);

CREATE TABLE favorita(
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         usuario_id INTEGER NOT NULL,
                         foliada_id INTEGER NOT NULL,
                         CONSTRAINT fk_usuario_fav FOREIGN KEY (usuario_id)
                             REFERENCES usuario(id) ON DELETE CASCADE,
                         CONSTRAINT fk_foliada_fav FOREIGN KEY (foliada_id)
                             REFERENCES foliada(id) ON DELETE CASCADE,
                         CONSTRAINT unique_favorita UNIQUE (usuario_id, foliada_id)
);

CREATE TABLE foliada_grupo(
                              foliada_id INTEGER NOT NULL,
                              grupo_id INTEGER NOT NULL,
                              PRIMARY KEY (foliada_id, grupo_id),
                              CONSTRAINT fk_foliada FOREIGN KEY (foliada_id)
                                  REFERENCES foliada(id) ON DELETE CASCADE,
                              CONSTRAINT fk_grupo FOREIGN KEY (grupo_id)
                                  REFERENCES grupo(id) ON DELETE CASCADE
);

-- ========================================
-- DATOS
-- ========================================
INSERT INTO provincia (nombre) VALUES
                                   ('A Coruña'),
                                   ('Lugo'),
                                   ('Ourense'),
                                   ('Pontevedra');

INSERT INTO usuario (nome, email, password) VALUES
                                                ('Admin', 'admin@foliadas.com', '1234'),
                                                ('Laura Gómez', 'laura@gmail.com', '1234'),
                                                ('Carlos Pérez', 'carlos@gmail.com', '1234'),
                                                ('Ana López', 'ana@gmail.com', '1234');

INSERT INTO grupo (nome, tipo, orixen) VALUES
                                           ('Tiruleque', 'Tradicional', 'Galicia'),
                                           ('Os Carecos', 'Tradicional', 'Galicia'),
                                           ('Felisa Segade', 'Vocal', 'Galicia'),
                                           ('Icía Varela', 'Vocal', 'Galicia'),
                                           ('Xosé Lois Romero', 'Tradicional', 'Galicia'),
                                           ('Aliboria', 'Tradicional', 'Galicia'),
                                           ('Alana', 'Tradicional', 'Galicia'),
                                           ('Lina e Lola', 'Tradicional', 'Galicia'),
                                           ('Requinta da Laxeira', 'Tradicional', 'Galicia'),
                                           ('SES', 'Moderno', 'Galicia'),
                                           ('Orquesta Bravú Xangai', 'Moderno', 'Galicia'),
                                           ('Fol da Chousa', 'Tradicional', 'Galicia'),
                                           ('Unto Vello', 'Tradicional', 'Galicia'),
                                           ('El Nido', 'Folk', 'Castela'),
                                           ('Delameseta', 'Folk', 'Castela'),
                                           ('Os Melidaos', 'Tradicional', 'Galicia'),
                                           ('De Ninghures', 'Folk', 'Galicia'),
                                           ('Baiuca', 'Electrónica Folk', 'Galicia'),
                                           ('Duendeneta', 'Folk', 'Galicia'),
                                           ('Os Charamuzas', 'Tradicional', 'Galicia'),
                                           ('Asubiños', 'Tradicional', 'Galicia'),
                                           ('Cantos da Valura', 'Tradicional', 'Galicia'),
                                           ('Son do Pucheiro', 'Tradicional', 'Galicia'),
                                           ('Noxo Me Das', 'Tradicional', 'Galicia'),
                                           ('Airiños da Freba', 'Tradicional', 'Galicia'),
                                           ('Pandereteiras O Fiadeiro', 'Tradicional', 'Galicia'),
                                           ('Os Carunchos', 'Tradicional', 'Galicia'),
                                           ('A Volta do Agro', 'Tradicional', 'Galicia'),
                                           ('Vimbio', 'Tradicional', 'Galicia'),
                                           ('Sabela', 'Vocal', 'Galicia'),
                                           ('A Banda da Balbina', 'Tradicional', 'Galicia'),
                                           ('Tumba e Dalle', 'Tradicional', 'Galicia'),
                                           ('Toxo Queimado', 'Tradicional', 'Galicia'),
                                           ('Son de Cores', 'Tradicional', 'Galicia'),
                                           ('Trasdalomba', 'Tradicional', 'Galicia'),
                                           ('Os do Trece', 'Tradicional', 'Galicia'),
                                           ('Xisco Feijoo', 'Tradicional', 'Galicia'),
                                           ('Charamusgas', 'Tradicional', 'Galicia'),
                                           ('Conhadeira', 'Tradicional', 'Galicia'),
                                           ('Os Pataghulhos', 'Tradicional', 'Galicia'),
                                           ('A Requinta de Lampai', 'Tradicional', 'Galicia'),
                                           ('Falperrys', 'Tradicional', 'Galicia'),
                                           ('Seitura', 'Tradicional', 'Galicia'),
                                           ('Storrentos', 'Tradicional', 'Galicia'),
                                           ('Pappaquino', 'Tradicional', 'Galicia'),
                                           ('Diego Cabaleiro', 'Tradicional', 'Galicia'),
                                           ('Ozocoreteiras', 'Tradicional', 'Galicia'),
                                           ('Pandereteiras de Maside', 'Tradicional', 'Galicia'),
                                           ('Velai Vai', 'Tradicional', 'Galicia'),
                                           ('Soalleira de Dorrón', 'Tradicional', 'Galicia'),
                                           ('Xarabal', 'Tradicional', 'Galicia'),
                                           ('Veira do Río', 'Tradicional', 'Galicia'),
                                           ('Os Zoqueiros', 'Tradicional', 'Galicia'),
                                           ('O Son do Río', 'Tradicional', 'Galicia'),
                                           ('Sobrosa-Paredes', 'Tradicional', 'Galicia'),
                                           ('Bouba', 'Tradicional', 'Galicia'),
                                           ('Lusco e Fusco', 'Tradicional', 'Galicia'),
                                           ('Son da Illa', 'Tradicional', 'Galicia'),
                                           ('Son de Peto', 'Tradicional', 'Galicia'),
                                           ('Treixadura', 'Tradicional', 'Galicia'),
                                           ('Ferriñas Bravas', 'Tradicional', 'Galicia');

INSERT INTO foliada (nome, fecha, hora, lugar, descripcion, latitude, lonxitude, provincia_id, imaxe) VALUES

                                                                                                   ('Foliada do Agro da Ponte', '2026-06-13', '20:00', 'Santa Comba', 'A Foliada do Agro da Ponte é unha celebración da música e cultura tradicional galega que reúne grupos, bailadores e público nun ambiente festivo e participativo en Santa Comba.', 43.0483, -8.8197, 1, '/images/1780428731554_AgroDaPonte.jpg'),
                                                                                                   ('Foliada de Melide', '2026-04-25', '12:00', 'Melide', 'A Foliada de Melide é un encontro de música e baile tradicional galego que reúne artistas e afeccionados para compartir a cultura popular nun ambiente festivo e aberto a todos os públicos.', 42.9136, -8.0146, 1, '/images/1780428820118_foliadaMelide.jpg'),
                                                                                                   ('Foliada de Raigañas', '2026-04-25', '13:00', 'Malpica', 'A Foliada Raigañas é un encontro de música e baile tradicional galego que se celebra en Malpica, reunindo grupos, músicos e público para compartir e promover a cultura popular galega nun ambiente festivo e participativo.', 43.3228, -8.8097, 1, NULL),
                                                                                                   ('Foliada á Xaneira', '2026-01-31', '20:30', 'Teo', 'A Foliada da Xaneira é unha celebración da música, o canto e o baile tradicional galego que se celebra en Teo, reunindo grupos e participantes de diferentes lugares para compartir a cultura popular nun ambiente festivo e de convivencia.', 42.8147, -8.5860, 1, NULL),
                                                                                                   ('XLII Dia da Muiñeira', '2026-06-07', '18:00', 'Carballo', 'O XL Día da Muiñeira de Carballo é unha xuntanza de música e baile tradicional galego centrada na muiñeira, que reúne agrupacións e bailadores de distintos puntos para celebrar e manter viva a danza popular nun ambiente festivo.', 43.2122, -8.6910, 1, NULL),
                                                                                                   ('NicraFolk', '2026-06-13', '20:30', 'Negreira', 'O Nicrafolk de Negreira é un festival de música folk e tradicional que reúne grupos e artistas para ofrecer concertos, actividades culturais e un ambiente festivo arredor da música de raíz en Negreira.', 42.9090, -8.7366, 1, NULL),
                                                                                                   ('Pasabodegas de Vedra', '2026-10-25', '17:00', 'Vedra', 'O Pasabodegas de Vedra é unha ruta festiva que combina viño, gastronomía e música tradicional, percorrendo distintas adegas do municipio nun ambiente lúdico e de convivencia.', 42.7785, -8.4677, 1, NULL),
                                                                                                   ('Foliada de Maristela', '2025-11-08', '20:00', 'Sobrado dos Monxes', 'A Foliada da Maristela de Sobrado dos Monxes é un encontro de música e baile tradicional galego que reúne grupos e participantes nun ambiente festivo para promover e manter viva a cultura popular.', 43.0378, -8.0278, 1, NULL),
                                                                                                   ('Ruada de Teixeiro', '2026-10-25', '20:00', 'Curtis', 'A Ruada de Teixeiro en Curtis é unha celebración de música e baile tradicional galego que reúne grupos e veciñanza nun encontro festivo e participativo na vila de Teixeiro.', 43.1245, -8.1479, 1, NULL),
                                                                                                   ('XVII Folk in Rio', '2026-07-19', NULL, 'Touro', 'O XVII Folk do Río de Touro é un festival de música folk que reúne grupos e artistas de música de raíz galega e outras tradicións, ofrecendo concertos e actividades nun ambiente festivo no municipio de Touro.', 42.8670, -8.3070, 1, NULL),

                                                                                                   ('Foliada da Fonsagrada', '2025-12-05', '11:00', 'A Fonsagrada', 'A Foliada da Fonsagrada é unha festa dedicada á música, ao baile e ás tradicións galegas, que reúne grupos e participantes de diferentes lugares para manter viva a cultura popular nun ambiente de convivencia e celebración.', 43.1233, -7.0676, 2, '/images/1780428951829_foliadaFonsagrada.jpg'),
                                                                                                   ('Foliada de Muimenta', '2026-06-06', '18:30', 'Cospeito', 'A Foliada de Muimenta (Cospeito) é un encontro de música e baile tradicional galego que reúne grupos e público nun ambiente festivo para celebrar e manter viva a cultura popular da zona.', 43.2367, -7.5615, 2, NULL),
                                                                                                   ('Cantigas na Rua', '2026-05-30', '10:00', 'Lugo', 'As Cantigas da Rúa de Lugo son unha iniciativa de música tradicional na rúa que reúne cantareiros e público no centro da cidade para compartir cantigas populares nun ambiente festivo e aberto.', 43.0097, -7.5560, 2, NULL),
                                                                                                   ('Cantos de Taberna de Becerreá', '2026-06-06', '19:00', 'Becerreá', 'Os Cantos de Taberna de Becerreá son unha ruta musical por bares e locais do municipio na que grupos e participantes interpretan cantigas tradicionais galegas nun ambiente festivo e de convivencia.', 42.8540, -7.1630, 2, NULL),
                                                                                                   ('Feira do 48', '2026-06-27', '18:00', 'Lugo', 'A Feira do 48 de Lugo é unha feira temática con ambiente festivo que combina postos, actividades culturais e música, converténdose nun punto de encontro social na cidade de Lugo.', 43.0097, -7.5560, 2, NULL),
                                                                                                   ('Foliada da Santa Mariña', '2026-07-03', NULL, 'Chantada', 'A Foliada da Santa Mariña de Chantada é unha festa de música e baile tradicional galego que reúne grupos e veciñanza nun ambiente festivo arredor da celebración popular da Santa Mariña.', 42.6080, -7.7710, 2, NULL),
                                                                                                   ('XIV Festival do Aturuxo', '2026-07-18', NULL, 'Ourol', 'O Festival Aturuxo de Ourol é un encontro de música folk e tradicional que reúne grupos e público nun ambiente festivo, con concertos e actividades arredor da cultura de raíz galega en Ourol.', 43.5640, -7.6400, 2, NULL),
                                                                                                   ('XLVII Festival de Pardiñas', '2026-07-31', '17:00', 'Guitiriz', 'O Festival de Pardiñas de Guitiriz é un dos festivais de música e cultura popular máis destacados de Galicia, que reúne concertos, foliada, obradoiros e actividades culturais arredor da música tradicional e folk.', 43.1819, -7.8950, 2, NULL),
                                                                                                   ('Foliada do Emigrante', '2025-08-02', '12:00', 'Baleira', 'A Foliada do Emigrante de Baleira é un encontro de música e baile tradicional galego que reúne veciñanza e participantes nun ambiente festivo de celebración da cultura popular e da memoria da emigración', 43.0156, -7.2390, 2, NULL),
                                                                                                   ('Foliada do Emigrante Barreiros', '2025-08-01', '20:00', 'Barreiros', 'A Foliada do Emigrante de Barreiros é unha celebración de música e baile tradicional galego que reúne grupos e público nun ambiente festivo de encontro e homenaxe á emigración.', 43.5140, -7.2330, 2, NULL),

                                                                                                   ('Fol-iada O Carballiño', '2026-05-23', '19:00', 'O Carballiño', 'A Foliada do Carballiño é un encontro de música e baile tradicional galego que reúne grupos, músicos e público nun ambiente festivo para promover a cultura popular e a convivencia.', 42.4310, -8.0780, 3, NULL),
                                                                                                   ('Foliada de Celavella', '2025-10-25', '20:00', 'Celanova', 'A Foliada de Celavella (Celanova) é un encontro de música e baile tradicional galego que reúne grupos e participantes nun ambiente festivo para celebrar e manter viva a cultura popular.', 42.1530, -7.9570, 3, NULL),
                                                                                                   ('Verbena Charamusgas', '2026-10-11', '13:00', 'Coles', 'A Verbena Charamusgas de Coles é unha festa popular con música en directo, baile e actividades festivas que reúne veciñanza e visitantes nun ambiente lúdico e de convivencia.', 42.4090, -7.8390, 3, NULL),
                                                                                                   ('Foliada da Escarocha', '2026-10-04', '11:30', 'Leiro', 'A Foliada da Escarocha (Leiro) é un encontro de música e baile tradicional galego que reúne grupos e público nun ambiente festivo para celebrar e manter viva a cultura popular.', 42.3720, -8.1230, 3, NULL),
                                                                                                   ('Serán dArnoia', '2026-06-06', '19:00', 'A Arnoia', 'O Serán da Arnoia é un encontro de música e baile tradicional galego que reúne veciñanza e grupos nun ambiente festivo de convivencia e celebración da cultura popular.', 42.2520, -8.1410, 3, NULL),
                                                                                                   ('Festa da Cuñeira', '2026-06-13', NULL, 'A Cuña', 'A Festa da Cuñeira (A Cuña) é unha celebración popular con música, actividades festivas e ambiente de convivencia que reúne veciñanza e visitantes arredor da tradición local.', 42.3360, -8.0680, 3, NULL),
                                                                                                   ('VenRespirar', '2026-06-19', '20:00', 'Ourense', 'O VenRespirar de Ourense é un evento cultural e festivo que combina música, actividades artísticas e propostas de lecer nun ambiente aberto e participativo na cidade de Ourense.', 42.3361, -7.8639, 3, NULL),
                                                                                                   ('Romaría Ponte Farruca', '2026-08-28', NULL, 'Laza', 'A Romaría da Ponte Farruca (Laza) é unha celebración tradicional galega que reúne veciñanza e visitantes arredor da música, o baile e as actividades populares nun ambiente festivo na contorna da Ponte Farruca.', 42.0610, -7.4610, 3, NULL),
                                                                                                   ('Ferreñas á Feira', '2026-06-20', '19:00', 'O Carballiño', 'As Ferreñas á Feira de O Carballiño son unha actividade musical e festiva de música tradicional galega que leva cantos e percusións á feira, creando un ambiente animado e participativo na vila.', 42.4310, -8.0780, 3, NULL),
                                                                                                   ('Serán de Castro de Beiro', '2026-06-06', '19:00', 'Castro de Beiro', 'O Serán de Castro de Beiro é un encontro de música e baile tradicional galego que reúne veciñanza e grupos nun ambiente festivo para manter viva a cultura popular da parroquia.', 42.3420, -7.8650, 3, NULL),

                                                                                                   ('Día da Muiñeira', '2026-05-29', '19:00', 'Pontevedra', 'O Día da Muiñeira de Pontevedra é unha celebración dedicada ao baile tradicional galego da muiñeira, que reúne agrupacións e bailadores nun encontro festivo na cidade.', 42.4310, -8.6440, 4, NULL),
                                                                                                   ('Serán do Chourizo á Sidra', '2026-05-29', '21:00', 'Bembrive', 'O Serán do Chourizo á Sidra de Benbrive é un encontro de música e baile tradicional galego que combina gastronomía e festa popular nun ambiente de convivencia e celebración da cultura local.', 42.2250, -8.7220, 4, NULL),
                                                                                                   ('Son da Louriña', '2026-05-30', '20:00', 'O Porriño', 'O Son da Louriña (O Porriño) é un encontro de música e baile tradicional galego que reúne veciñanza e grupos nun ambiente festivo para celebrar a cultura popular da comarca.', 42.1610, -8.6190, 4, NULL),
                                                                                                   ('Festival de Alborexar', '2026-05-30', '21:00', 'Mondariz', 'O Festival Alborexar de Mondariz é un encontro de música folk e tradicional que reúne grupos e público nun ambiente festivo arredor da cultura de raíz galega no municipio de Mondariz.', 42.2320, -8.4670, 4, NULL),
                                                                                                   ('Foliada da Pedreira', '2026-06-05', '21:00', 'Pontevedra', 'A Foliada da Pedreira (Pontevedra) é un encontro de música e baile tradicional galego que reúne grupos e veciñanza nun ambiente festivo para celebrar e manter viva a cultura popular.', 42.4310, -8.6440, 4, NULL),
                                                                                                   ('Cantos de Taberna na Arousa', '2026-06-06', '20:00', 'Illa de Arousa', 'Os Cantos de Taberna na Arousa (Illa de Arousa) son unha ruta musical por locais da illa na que grupos e participantes interpretan música tradicional galega nun ambiente festivo e participativo.', 42.5640, -8.8640, 4, NULL),
                                                                                                   ('Foliada de Domaio', '2026-11-15', '18:00', 'Moaña', 'A Foliada de Domaio (Moaña) é un encontro de música e baile tradicional galego que reúne grupos e veciñanza nun ambiente festivo para celebrar e manter viva a cultura popular da parroquia.', 42.2850, -8.7440, 4, NULL),
                                                                                                   ('Eferro Foliada', '2025-09-13', '12:30', 'Vila de Cruces', 'O Eferro Foliada de Vila de Cruces é un encontro de música e baile tradicional galego que reúne grupos e público nun ambiente festivo arredor da cultura de raíz e a convivencia.', 42.7940, -8.1700, 4, NULL),
                                                                                                   ('Serán da Buxaina', '2026-07-26', '20:00', 'Coruxo', 'O Serán da Buxaina (Coruxo) é un encontro de música e baile tradicional galego que reúne veciñanza e grupos nun ambiente festivo para celebrar e manter viva a cultura popular da parroquia.', 42.2010, -8.7700, 4, NULL),
                                                                                                   ('Foliada do Piñeiriño', '2026-06-13', '11:00', 'Vilagarcía de Arousa', 'A Foliada do Piñeiriño (Vilagarcía de Arousa) é un encontro de música e baile tradicional galego que reúne grupos e veciñanza nun ambiente festivo para celebrar e promover a cultura popular', 42.5930, -8.7640, 4, NULL);

INSERT INTO foliada_grupo (foliada_id, grupo_id) VALUES
                                                     (2, 1),
                                                     (2, 2),
                                                     (2, 3),
                                                     (3, 4),
                                                     (6, 5),
                                                     (6, 6),
                                                     (6, 7),
                                                     (6, 8),
                                                     (7, 9),
                                                     (7, 10),
                                                     (7, 11),
                                                     (7, 12),
                                                     (11, 13),
                                                     (11, 14),
                                                     (11, 15),
                                                     (11, 16),
                                                     (11, 17),
                                                     (11, 18),
                                                     (11, 19),
                                                     (12, 20),
                                                     (12, 21),
                                                     (12, 22),
                                                     (12, 23),
                                                     (12, 24),
                                                     (15, 25),
                                                     (15, 26),
                                                     (15, 27),
                                                     (15, 28),
                                                     (17, 29),
                                                     (17, 30),
                                                     (17, 31),
                                                     (17, 32),
                                                     (19, 33),
                                                     (19, 34),
                                                     (19, 35),
                                                     (19, 36),
                                                     (23, 37),
                                                     (23, 38),
                                                     (23, 39),
                                                     (24, 40),
                                                     (24, 41),
                                                     (26, 42),
                                                     (26, 43),
                                                     (26, 44),
                                                     (26, 45),
                                                     (28, 5),
                                                     (28, 6),
                                                     (29, 46),
                                                     (29, 47),
                                                     (29, 48),
                                                     (29, 49),
                                                     (31, 50),
                                                     (33, 51),
                                                     (33, 52),
                                                     (33, 53),
                                                     (34, 54),
                                                     (34, 55),
                                                     (35, 56),
                                                     (36, 57),
                                                     (36, 58),
                                                     (36, 59),
                                                     (38, 60),
                                                     (38, 17),
                                                     (38, 19),
                                                     (40, 61);

INSERT INTO favorita (usuario_id, foliada_id) VALUES
                                                  (1, 1),
                                                  (1, 2),
                                                  (2, 1),
                                                  (2, 3),
                                                  (3, 2),
                                                  (3, 4),
                                                  (4, 4);