-- ========================================
-- TABLAS
-- ========================================
CREATE TABLE provincia(
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE usuario(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(100) NOT NULL,
                        email VARCHAR(100) UNIQUE NOT NULL,
                        password VARCHAR(255) NOT NULL
);

CREATE TABLE grupo(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nome VARCHAR(100) NOT NULL,
                      tipo VARCHAR(50),
                      orixen VARCHAR(100)
);

CREATE TABLE foliada(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(150) NOT NULL,
                        fecha DATE NOT NULL,
                        hora TIME,
                        lugar VARCHAR(150),
                        descripcion TEXT,
                        latitude DECIMAL(9,6),
                        lonxitude DECIMAL(9,6),
                        provincia_id INTEGER,
                        CONSTRAINT fk_provincia FOREIGN KEY (provincia_id)
                            REFERENCES provincia(id) ON DELETE SET NULL
);

CREATE TABLE favorita(
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         usuario_id INTEGER NOT NULL,
                         foliada_id INTEGER NOT NULL,
                         CONSTRAINT fk_usuario_fav FOREIGN KEY (usuario_id)
                             REFERENCES usuario(id) ON DELETE CASCADE,
                         CONSTRAINT fk_foliada_fav FOREIGN KEY (foliada_id)
                             REFERENCES foliada(id) ON DELETE CASCADE,
                         CONSTRAINT unique_favorita UNIQUE (usuario_id, foliada_id)
);

CREATE TABLE foliada_grupo(
                              foliada_id INTEGER NOT NULL,
                              grupo_id INTEGER NOT NULL,
                              PRIMARY KEY (foliada_id, grupo_id),
                              CONSTRAINT fk_foliada FOREIGN KEY (foliada_id)
                                  REFERENCES foliada(id) ON DELETE CASCADE,
                              CONSTRAINT fk_grupo FOREIGN KEY (grupo_id)
                                  REFERENCES grupo(id) ON DELETE CASCADE
);

-- ========================================
-- DATOS
-- ========================================
INSERT INTO provincia (nombre) VALUES
                                   ('A Coruña'),
                                   ('Lugo'),
                                   ('Ourense'),
                                   ('Pontevedra');

INSERT INTO usuario (nome, email, password) VALUES
                                                ('Admin', 'admin@foliadas.com', '1234'),
                                                ('Laura Gómez', 'laura@gmail.com', '1234'),
                                                ('Carlos Pérez', 'carlos@gmail.com', '1234'),
                                                ('Ana López', 'ana@gmail.com', '1234');

INSERT INTO grupo (nome, tipo, orixen) VALUES
                                           ('Tiruleque', 'Tradicional', 'Galicia'),
                                           ('Os Carecos', 'Tradicional', 'Galicia'),
                                           ('Felisa Segade', 'Vocal', 'Galicia'),
                                           ('Icía Varela', 'Vocal', 'Galicia'),
                                           ('Xosé Lois Romero', 'Tradicional', 'Galicia'),
                                           ('Aliboria', 'Tradicional', 'Galicia'),
                                           ('Alana', 'Tradicional', 'Galicia'),
                                           ('Lina e Lola', 'Tradicional', 'Galicia'),
                                           ('Requinta da Laxeira', 'Tradicional', 'Galicia'),
                                           ('SES', 'Moderno', 'Galicia'),
                                           ('Orquesta Bravú Xangai', 'Moderno', 'Galicia'),
                                           ('Fol da Chousa', 'Tradicional', 'Galicia'),
                                           ('Unto Vello', 'Tradicional', 'Galicia'),
                                           ('El Nido', 'Folk', 'Castela'),
                                           ('Delameseta', 'Folk', 'Castela'),
                                           ('Os Melidaos', 'Tradicional', 'Galicia'),
                                           ('De Ninghures', 'Folk', 'Galicia'),
                                           ('Baiuca', 'Electrónica Folk', 'Galicia'),
                                           ('Duendeneta', 'Folk', 'Galicia'),
                                           ('Os Charamuzas', 'Tradicional', 'Galicia'),
                                           ('Asubiños', 'Tradicional', 'Galicia'),
                                           ('Cantos da Valura', 'Tradicional', 'Galicia'),
                                           ('Son do Pucheiro', 'Tradicional', 'Galicia'),
                                           ('Noxo Me Das', 'Tradicional', 'Galicia'),
                                           ('Airiños da Freba', 'Tradicional', 'Galicia'),
                                           ('Pandereteiras O Fiadeiro', 'Tradicional', 'Galicia'),
                                           ('Os Carunchos', 'Tradicional', 'Galicia'),
                                           ('A Volta do Agro', 'Tradicional', 'Galicia'),
                                           ('Vimbio', 'Tradicional', 'Galicia'),
                                           ('Sabela', 'Vocal', 'Galicia'),
                                           ('A Banda da Balbina', 'Tradicional', 'Galicia'),
                                           ('Tumba e Dalle', 'Tradicional', 'Galicia'),
                                           ('Toxo Queimado', 'Tradicional', 'Galicia'),
                                           ('Son de Cores', 'Tradicional', 'Galicia'),
                                           ('Trasdalomba', 'Tradicional', 'Galicia'),
                                           ('Os do Trece', 'Tradicional', 'Galicia'),
                                           ('Xisco Feijoo', 'Tradicional', 'Galicia'),
                                           ('Charamusgas', 'Tradicional', 'Galicia'),
                                           ('Conhadeira', 'Tradicional', 'Galicia'),
                                           ('Os Pataghulhos', 'Tradicional', 'Galicia'),
                                           ('A Requinta de Lampai', 'Tradicional', 'Galicia'),
                                           ('Falperrys', 'Tradicional', 'Galicia'),
                                           ('Seitura', 'Tradicional', 'Galicia'),
                                           ('Storrentos', 'Tradicional', 'Galicia'),
                                           ('Pappaquino', 'Tradicional', 'Galicia'),
                                           ('Diego Cabaleiro', 'Tradicional', 'Galicia'),
                                           ('Ozocoreteiras', 'Tradicional', 'Galicia'),
                                           ('Pandereteiras de Maside', 'Tradicional', 'Galicia'),
                                           ('Velai Vai', 'Tradicional', 'Galicia'),
                                           ('Soalleira de Dorrón', 'Tradicional', 'Galicia'),
                                           ('Xarabal', 'Tradicional', 'Galicia'),
                                           ('Veira do Río', 'Tradicional', 'Galicia'),
                                           ('Os Zoqueiros', 'Tradicional', 'Galicia'),
                                           ('O Son do Río', 'Tradicional', 'Galicia'),
                                           ('Sobrosa-Paredes', 'Tradicional', 'Galicia'),
                                           ('Bouba', 'Tradicional', 'Galicia'),
                                           ('Lusco e Fusco', 'Tradicional', 'Galicia'),
                                           ('Son da Illa', 'Tradicional', 'Galicia'),
                                           ('Son de Peto', 'Tradicional', 'Galicia'),
                                           ('Treixadura', 'Tradicional', 'Galicia'),
                                           ('Ferriñas Bravas', 'Tradicional', 'Galicia');

INSERT INTO foliada (nome, fecha, hora, lugar, descripcion, latitude, lonxitude, provincia_id) VALUES

                                                                                                   ('Foliada do Agro da Ponte', '2026-06-13', '20:00', 'Santa Comba', '', 43.0483, -8.8197, 1),
                                                                                                   ('Foliada de Melide', '2026-04-25', '12:00', 'Melide', '', 42.9136, -8.0146, 1),
                                                                                                   ('Foliada de Raigañas', '2026-04-25', '13:00', 'Malpica', '', 43.3228, -8.8097, 1),
                                                                                                   ('Foliada á Xaneira', '2026-01-31', '20:30', 'Teo', '', 42.8147, -8.5860, 1),
                                                                                                   ('XLII Dia da Muiñeira', '2026-06-07', '18:00', 'Carballo', '', 43.2122, -8.6910, 1),
                                                                                                   ('NicraFolk', '2026-06-13', '20:30', 'Negreira', '', 42.9090, -8.7366, 1),
                                                                                                   ('Pasabodegas de Vedra', '2026-10-25', '17:00', 'Vedra', '', 42.7785, -8.4677, 1),
                                                                                                   ('Foliada de Maristela', '2025-11-08', '20:00', 'Sobrado dos Monxes', '', 43.0378, -8.0278, 1),
                                                                                                   ('Ruada de Teixeiro', '2026-10-25', '20:00', 'Curtis', '', 43.1245, -8.1479, 1),
                                                                                                   ('XVII Folk in Rio', '2026-07-19', NULL, 'Touro', '', 42.8670, -8.3070, 1),

                                                                                                   ('Foliada da Fonsagrada', '2025-12-05', '11:00', 'A Fonsagrada', '', 43.1233, -7.0676, 2),
                                                                                                   ('Foliada de Muimenta', '2026-06-06', '18:30', 'Cospeito', '', 43.2367, -7.5615, 2),
                                                                                                   ('Cantigas na Rua', '2026-05-30', '10:00', 'Lugo', '', 43.0097, -7.5560, 2),
                                                                                                   ('Cantos de Taberna de Becerreá', '2026-06-06', '19:00', 'Becerreá', '', 42.8540, -7.1630, 2),
                                                                                                   ('Feira do 48', '2026-06-27', '18:00', 'Lugo', '', 43.0097, -7.5560, 2),
                                                                                                   ('Foliada da Santa Mariña', '2026-07-03', NULL, 'Chantada', '', 42.6080, -7.7710, 2),
                                                                                                   ('XIV Festival do Aturuxo', '2026-07-18', NULL, 'Ourol', '', 43.5640, -7.6400, 2),
                                                                                                   ('XLVII Festival de Pardiñas', '2026-07-31', '17:00', 'Guitiriz', '', 43.1819, -7.8950, 2),
                                                                                                   ('Foliada do Emigrante', '2025-08-02', '12:00', 'Baleira', '', 43.0156, -7.2390, 2),
                                                                                                   ('Foliada do Emigrante Barreiros', '2025-08-01', '20:00', 'Barreiros', '', 43.5140, -7.2330, 2),

                                                                                                   ('Fol-iada O Carballiño', '2026-05-23', '19:00', 'O Carballiño', '', 42.4310, -8.0780, 3),
                                                                                                   ('Foliada de Celavella', '2025-10-25', '20:00', 'Celanova', '', 42.1530, -7.9570, 3),
                                                                                                   ('Verbena Charamusgas', '2026-10-11', '13:00', 'Coles', '', 42.4090, -7.8390, 3),
                                                                                                   ('Foliada da Escarocha', '2026-10-04', '11:30', 'Leiro', '', 42.3720, -8.1230, 3),
                                                                                                   ('Serán dArnoia', '2026-06-06', '19:00', 'A Arnoia', '', 42.2520, -8.1410, 3),
                                                                                                   ('Festa da Cuñeira', '2026-06-13', NULL, 'A Cuña', '', 42.3360, -8.0680, 3),
                                                                                                   ('VenRespirar', '2026-06-19', '20:00', 'Ourense', '', 42.3361, -7.8639, 3),
                                                                                                   ('Romaría Ponte Farruca', '2026-08-28', NULL, 'Laza', '', 42.0610, -7.4610, 3),
                                                                                                   ('Ferreñas á Feira', '2026-06-20', '19:00', 'O Carballiño', '', 42.4310, -8.0780, 3),
                                                                                                   ('Serán de Castro de Beiro', '2026-06-06', '19:00', 'Castro de Beiro', '', 42.3420, -7.8650, 3),

                                                                                                   ('Día da Muiñeira', '2026-05-29', '19:00', 'Pontevedra', '', 42.4310, -8.6440, 4),
                                                                                                   ('Serán do Chourizo á Sidra', '2026-05-29', '21:00', 'Bembrive', '', 42.2250, -8.7220, 4),
                                                                                                   ('Son da Louriña', '2026-05-30', '20:00', 'O Porriño', '', 42.1610, -8.6190, 4),
                                                                                                   ('Festival de Alborexar', '2026-05-30', '21:00', 'Mondariz', '', 42.2320, -8.4670, 4),
                                                                                                   ('Foliada da Pedreira', '2026-06-05', '21:00', 'Pontevedra', '', 42.4310, -8.6440, 4),
                                                                                                   ('Cantos de Taberna na Arousa', '2026-06-06', '20:00', 'Illa de Arousa', '', 42.5640, -8.8640, 4),
                                                                                                   ('Foliada de Domaio', '2026-11-15', '18:00', 'Moaña', '', 42.2850, -8.7440, 4),
                                                                                                   ('Eferro Foliada', '2025-09-13', '12:30', 'Vila de Cruces', '', 42.7940, -8.1700, 4),
                                                                                                   ('Serán da Buxaina', '2026-07-26', '20:00', 'Coruxo', '', 42.2010, -8.7700, 4),
                                                                                                   ('Foliada do Piñeiriño', '2026-06-13', '11:00', 'Vilagarcía de Arousa', '', 42.5930, -8.7640, 4);

INSERT INTO foliada_grupo (foliada_id, grupo_id) VALUES
                                                     (2, 1),
                                                     (2, 2),
                                                     (2, 3),
                                                     (3, 4),
                                                     (6, 5),
                                                     (6, 6),
                                                     (6, 7),
                                                     (6, 8),
                                                     (7, 9),
                                                     (7, 10),
                                                     (7, 11),
                                                     (7, 12),
                                                     (11, 13),
                                                     (11, 14),
                                                     (11, 15),
                                                     (11, 16),
                                                     (11, 17),
                                                     (11, 18),
                                                     (11, 19),
                                                     (12, 20),
                                                     (12, 21),
                                                     (12, 22),
                                                     (12, 23),
                                                     (12, 24),
                                                     (15, 25),
                                                     (15, 26),
                                                     (15, 27),
                                                     (15, 28),
                                                     (17, 29),
                                                     (17, 30),
                                                     (17, 31),
                                                     (17, 32),
                                                     (19, 33),
                                                     (19, 34),
                                                     (19, 35),
                                                     (19, 36),
                                                     (23, 37),
                                                     (23, 38),
                                                     (23, 39),
                                                     (24, 40),
                                                     (24, 41),
                                                     (26, 42),
                                                     (26, 43),
                                                     (26, 44),
                                                     (26, 45),
                                                     (28, 5),
                                                     (28, 6),
                                                     (29, 46),
                                                     (29, 47),
                                                     (29, 48),
                                                     (29, 49),
                                                     (31, 50),
                                                     (33, 51),
                                                     (33, 52),
                                                     (33, 53),
                                                     (34, 54),
                                                     (34, 55),
                                                     (35, 56),
                                                     (36, 57),
                                                     (36, 58),
                                                     (36, 59),
                                                     (38, 60),
                                                     (38, 17),
                                                     (38, 19),
                                                     (40, 61);

INSERT INTO favorita (usuario_id, foliada_id) VALUES
                                                  (1, 1),
                                                  (1, 2),
                                                  (2, 1),
                                                  (2, 3),
                                                  (3, 2),
                                                  (3, 4),
                                                  (4, 4);